#server:
#  port: 9090

path.name: /

spring:
  application:
    name: ProductApi

  datasource:
    url: jdbc:h2:mem:productApi;Mode=Oracle
    platform: h2
    enable: true
    path: /h2-console

  #access h2: localhost:9090/h2-console
  #url: jdbc:h2:mem:productapi
  #add devtool dependency to pom
  # access swagger: localhost:8080/swagger-ui/index.html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
